name: "Keepalive Workflow"
on:
  workflow_dispatch:
  schedule:
    - cron: "35 22 * * *"
permissions:
  actions: write
jobs:
  cronjob-based-github-action:
    name: "Keepalive Workflow"
    runs-on: ubuntu-latest
    steps:
      - uses: "gautamkrishnar/keepalive-workflow@v2"
        with:
          workflow_files: "production_publish-image.yaml"
          time_elapsed: "0"
